require 'test/unit' 

require_relative 'being_test'
require_relative 'cave_test'
require_relative 'map_test' 
require_relative 'minotaurus_test'
require_relative 'options_test'
require_relative 'runner_test' 
require_relative 'theseus_test'
require_relative 'tunnel_test'
