require 'rubygems'
require 'rubygems/package_task'
require 'rake'
require 'rake/clean'
require 'rdoc/task'
require 'rake/testtask'

spec = Gem::Specification.new do |s|
  s.name = 'RUB_sp_Theseus_a_Minotaurus'
  s.version = '0.0.1'
  s.has_rdoc = true
  s.extra_rdoc_files = ['README', 'LICENSE']
  s.summary = 'Your summary here'
  s.description = s.summary
  s.author = ''
  s.email = 'hybljan2@gmail.com'
  s.executables = ['bin/thamin.rb']
  s.files = %w(README Rakefile) + Dir.glob("{bin,lib,spec}/**/*")
  s.require_path = ""
  s.bindir = "bin"  
  s.add_dependency('test-unit', '>= 2.4.5')
end

Gem::PackageTask.new(spec) do |p|
  p.gem_spec = spec
  p.need_tar = true
  p.need_zip = true
end

RDoc::Task.new do |rdoc|
  files =['README', 'LICENSE', 'lib/**/*.rb']
  rdoc.rdoc_files.add(files)
  rdoc.main = "README" # page to start on
  rdoc.title = "RUB_sp_Theseus_a_Minotaurus Docs"
  rdoc.rdoc_dir = 'doc/rdoc' # rdoc output folder
  rdoc.options << '--line-numbers'
end

Rake::TestTask.new do |t|
  t.libs << "test-unit"
  t.test_files = FileList['test/**/*.rb']
end